# Generated by Django 3.0.4 on 2020-03-25 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arena',
            name='places',
        ),
        migrations.RemoveField(
            model_name='arena',
            name='users',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='places',
        ),
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delivery_data',
        ),
        migrations.AddField(
            model_name='arena',
            name='places_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ticket_system.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverydata',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ticket_system.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ticket_arena',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ticket_system.Arena'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arena',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
