# Generated by Django 3.0.4 on 2020-03-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0002_auto_20200326_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='deliverydata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ticket_arena',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='DeliveryData',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
