# Generated by Django 3.0.4 on 2020-03-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0003_auto_20200326_0016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArenaManager',
        ),
    ]
