# Generated by Django 3.0.4 on 2020-03-26 02:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0004_delete_arenamanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0)),
                ('reservation_time', models.DateTimeField(verbose_name=datetime.datetime(2020, 3, 26, 3, 9, 24, 524945))),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=8, unique=True)),
                ('last_active', models.DateTimeField(verbose_name='last active')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('street', models.CharField(default='', max_length=50)),
                ('home_number', models.CharField(default='', max_length=50)),
                ('post_code', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerIPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20)),
                ('time_logged', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticket_system.Buyer')),
            ],
        ),
        migrations.DeleteModel(
            name='Arena',
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('AV', 'Available'), ('SL', 'Sold'), ('SE', 'Selected'), ('RE', 'Reserved')], default='AV', max_length=2),
        ),
        migrations.AddField(
            model_name='basket',
            name='basket_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket_system.Buyer'),
        ),
        migrations.AddField(
            model_name='place',
            name='in_basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ticket_system.Basket'),
        ),
    ]
