# Generated by Django 3.0.4 on 2020-04-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0006_auto_20200326_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='reservation_expires',
            field=models.DateTimeField(null=True),
        ),
    ]
