# Generated by Django 3.0.4 on 2020-04-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0007_place_reservation_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='reservation_expires',
        ),
    ]
