# Generated by Django 3.0.4 on 2020-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('birth', models.DateField()),
                ('weight', models.FloatField()),
                ('category', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('has_belt', models.BooleanField(default=False)),
                ('wins', models.IntegerField()),
                ('losts', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=20)),
                ('link_url', models.CharField(max_length=200)),
            ],
        ),
    ]
