# Generated by Django 3.0.4 on 2020-04-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fight_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=20)),
                ('link_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.AddField(
            model_name='fighter',
            name='image',
            field=models.FileField(blank=True, upload_to='fighters_img'),
        ),
        migrations.AddField(
            model_name='fighter',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fighter',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mężczyzna'), (2, 'Kobieta')], default=1),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fighterlinks',
            name='fighter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fight_service.Fighter'),
        ),
    ]
