# Generated by Django 3.0.4 on 2020-04-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fight_service', '0002_auto_20200401_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FighterLinks',
            new_name='FighterLink',
        ),
    ]
