# Generated by Django 3.0.4 on 2020-04-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight_service', '0003_auto_20200401_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='birth',
            field=models.DateField(verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='category',
            field=models.CharField(max_length=10, verbose_name='Kategoria wagowa'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='draws',
            field=models.IntegerField(verbose_name='Zremisowane'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='has_belt',
            field=models.BooleanField(default=False, verbose_name='Czy posiada pas mistrzowski?'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='image',
            field=models.FileField(blank=True, upload_to='fighters_img', verbose_name='Zdjęcie zawodnika'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='losts',
            field=models.IntegerField(verbose_name='Przegrane'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Imie'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Czy opublikować na stronie?'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='sex',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Mężczyzna'), (2, 'Kobieta')], default=1, verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='weight',
            field=models.FloatField(verbose_name='Waga'),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='wins',
            field=models.IntegerField(verbose_name='Wygrane'),
        ),
    ]
