# Generated by Django 3.0.4 on 2020-04-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight_service', '0004_auto_20200401_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priorytet'),
        ),
        migrations.AlterField(
            model_name='fighterlink',
            name='link_name',
            field=models.CharField(max_length=20, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='fighterlink',
            name='link_url',
            field=models.CharField(max_length=200, verbose_name='Adres linku'),
        ),
    ]
