# Generated by Django 3.0.4 on 2020-04-01 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fight_service', '0005_auto_20200401_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='img_url',
        ),
    ]
