# Generated by Django 3.0.4 on 2020-04-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight_service', '0006_remove_fighter_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='height',
            field=models.FloatField(default=0, verbose_name='Wzrost'),
        ),
    ]
