# Generated by Django 3.0.4 on 2020-04-02 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fight_service', '0007_fighter_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighterlink',
            name='fighter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='links', to='fight_service.Fighter'),
        ),
    ]
