# Generated by Django 3.0.4 on 2020-04-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fight_service', '0008_auto_20200402_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fighterlink',
            old_name='link_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fighterlink',
            old_name='link_url',
            new_name='url',
        ),
    ]
