# Generated by Django 3.0.4 on 2020-04-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight_service', '0010_auto_20200402_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='draws',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zremisowane'),
        ),
    ]
