# Generated by Django 3.0.4 on 2020-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight_service', '0012_auto_20200406_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightcards',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Czy opublikować na stronie?'),
        ),
        migrations.AddField(
            model_name='fightcards',
            name='set_hidden',
            field=models.BooleanField(default=True, verbose_name='Czy opublikować jako ukrytą?'),
        ),
    ]
